rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - ruby-head
 - ree
 - rbx-18mode

gemfile:
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile

before_script:
  - "mysql -e 'create database carrierwave_test;'"
