before_install:
  - gem install bundler

notifications:
  email: false

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.5
 - ruby-head
 - jruby
 - jruby-head

gemfile:
  - Gemfile
  - gemfiles/rails-3-2-stable.gemfile
  - gemfiles/rails-4-0-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-master.gemfile

matrix:
  allow_failures:
    rvm:
      - ruby-head
      - jruby-head


before_script:
  - "mysql -e 'create database carrierwave_test;'"
